name: Hello World
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-actions-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Print git env
        run: |
          echo "Hello World!"
          echo ${{ github.repository }}
          echo ${{ github.run_id }}
          echo ${{ github.event.number }}
          echo ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR comment
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
