name: Hello World
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-actions-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Print git env
        run: |
          echo "Hello World!"
          echo ${{ github.repository }}
          echo ${{ github.run_id }}
