name: Hello World
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-actions-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Print git env
        run: |
          cat  << EOF > comment.md
          ## Test Failed
          The tests failed. Please check the logs for more information.
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
      - name: Check env
        run: |
          which gh
          gh --version
      - name: Create PR comment
        run: |
          gh pr comment ${{ github.event.number }} -F comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
