name: Hello World
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-actions-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"