name: Hello World
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-github-actions-test-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Print git env
        run: |
          echo "ok" > comment.md
      - name: Check env
        run: |
          which gh
          gh --version
      - name: Create PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.number }} -F comment.md
